### ISSUE TITLE
gmqcc is FTBFS with gcc 7.0

### ISSUE THREAD

**Issue by ignatenkobrain** [graphitemaster/gmqcc#174]
```c
stat.c: In function 'util_hthash':
stat.c:431:15: error: this statement may fall through [-Werror=implicit-fallthrough=]
             k ^= tail[2] << 16;
             ~~^~~~~~~~~~~~~~~~
stat.c:432:9: note: here
         case 2:
         ^~~~
stat.c:433:15: error: this statement may fall through [-Werror=implicit-fallthrough=]
             k ^= tail[1] << 8;
             ~~^~~~~~~~~~~~~~~
stat.c:434:9: note: here
         case 1:
         ^~~~
```

**Comment by Blub** [comment]
I currently don't actually have gcc7 around to test this though, so I'll test later unless you're faster ;-)
Would tag a 0.3.6 bugfix release then.
(Would be nicer though if we finish the c++ migration in the master branch and release that but we're working on that on a very irregular basis...)

**Comment by Blub** [comment]
Okay, looks like the 2nd try caught 'em all. Also we're disabling `-Werror` on the stable branch for now...

**Comment by graphitemaster** [comment]
This seems fixed now
