### ISSUE TITLE
Broken XOR assign

### ISSUE THREAD

**Issue by martin-t** [graphitemaster/gmqcc#190]
Both prints should give the same result.

```C
void main() {
    vector v1 = '1 2 3';
    vector v2 = '5 5 5';
    print(vtos(v1 ^ v2));

    v1 ^= v2;
    print(vtos(v1));
}
```

**Comment by graphitemaster** [comment]
So this only breaks with optimizations `-O3` and it appears to be a peephole optimization done by `ir_function_pass_peephole`. There's a litany of tests done here to avoid the optimization from being done:
```cpp
                /* only do it for SSA values */
                if (value->m_store != store_value)
                    continue;

                /* don't optimize out the temp if it's used later again */
                if (value->m_reads.size() != 1)
                    continue;

                /* The very next store must use this value */
                if (value->m_reads[0] != store)
                    continue;

                /* And of course the store must _read_ from it, so it's in
                 * OP 1 */
                if (store->_m_ops[1] != value)
                    continue;
```
But `VINSTR_*` never appear to trigger any of them. Upon further digging I think it has to do with the last check there, the IR optimizer is assuming that OP1 of the store operation is going to be the value of the `VINSTR_*` but the way `VINSTR_*` work has a different operand order (I can't quite tell why either.) As you can see here
```cpp
        if (instr->m_opcode == VINSTR_BITXOR) {
            stmt.opcode = INSTR_BITOR;
            stmt.o1.s1 = instr->_m_ops[1]->codeAddress();
            stmt.o2.s1 = instr->_m_ops[2]->codeAddress();
            stmt.o3.s1 = instr->_m_ops[0]->codeAddress();
```
This indicates that OP1 is actually being given to OP0 and the actual OP1 is `_m_ops[2]`. There's some special casing made in the IR too for the `VINSTR_*` that deal with attaching life ranges, not sure if that has anything to do with it as well.
