### ISSUE TITLE
if(cond) + break; issue with -O3

### ISSUE THREAD

**Issue by terencehill** [graphitemaster/gmqcc#198]
This code doesn't compile with `./gmqcc -std=gmqcc -O3 mycode.qc -o out.dat && ./qcvm out.dat`. with the error `unreachable statement` at the lines with comment. It does compile without the -03 flag.

```
void main() {
	while (1) // unreachable statement
	{
		if (1)
			break;
	}
}
```

```
void main() {
	float i = 0;
	while (1)
	{
		if (1)
		{
			if (1) // unreachable statement
				i = 1;
			break;
		}
	}
}
```

**Comment by graphitemaster** [comment]
Fixed by 71138cb
